### ISSUE TITLE
You cannot auth exceed once in 60 seconds error.

### ISSUE THREAD

**Issue by edwolfe3** [unparagoned/cloudtuya#16]
Just started about a couple weeks ago.

```
 njstuya booting njstuya +0ms
  njstuya "{argName} value is: 06200045dc4f2236e565_2 +5ms
  njstuya "{argName} value is: cloud +0ms
  njstuya api {"userName":"[blanked]","password":"[blanked]","countryCode":"1","bizType":"smart_life","region":"us"} or [blanked] +3ms
  cloudtuya {"responseStatus":"error","errorMsg":"you cannot auth exceed once in 60 seconds"} +0ms
  cloudtuya {
  cloudtuya   responseStatus: 'error',
  cloudtuya   errorMsg: 'you cannot auth exceed once in 60 seconds'
  cloudtuya } +2ms
  njstuya Token {"responseStatus":"error","errorMsg":"you cannot auth exceed once in 60 seconds"} +496ms
  cloudtuya { devId: '06200045dc4f2236e565_2' } +5ms
  cloudtuya INVAILD_REQUEST_2 +450ms
(node:4481) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'devices' of undefined
    at CloudTuya.find (/etc/openhab2/scripts/node_modules/cloudtuya/cloudtuya.js:101:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async CloudTuya.state (/etc/openhab2/scripts/node_modules/cloudtuya/cloudtuya.js:147:19)
    at async runCloud (/etc/openhab2/scripts/node_modules/njstuya/njstuya.js:206:26)
(node:4481) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4481) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by unparagoned** [comment]
This is because tuya has restricted authentication to once in 60 seconds. I've updated cloudtuya with a function setToken. So basically you need to save the token from a login, make sure it's not too old and then reuse the token instead of logging in again. Have a look at njsTuya https://github.com/unparagoned/njsTuya/blob/master/njstuya.js for details(although I think it might be broken in njsTuya if you are using openhab due to write permissions).
```
  let tokens;
  try{
    tokens = JSON.parse(fs.readFileSync('./cloudToken.json'));
    debug(`cloud Token Catch ${JSON.stringify(tokens)}`);
    if(tokens.valid_to < Date.now() + 10) throw ('update token');
    api.setToken(tokens);
  } catch(err) {
    debug(err);
    tokens = await api.login();
    tokens.valid_to = Date.now() + tokens.expires_in;
    fs.writeFileSync(`./cloudToken.json`, JSON.stringify(tokens));
  }

```

**Comment by edwolfe3** [comment]
I'm calling it from the command line from an OpenHab script. Does that mean I can no longer use it with openhab? If so, how do I get the token and what command line argument to set the token?

**Comment by unparagoned** [comment]
The latest version of njsTuya saves the authentication token and should reuse it if valid.

**Comment by edwolfe3** [comment]
I believe I already have the latest how can I verify that?

**Comment by unparagoned** [comment]
Upgrade using ```npm upgrade njstuya```
Check the versions using, should be 2.3.5 and 1.07
```
cat node_modules/njstuya/package.json
cat node_modules/cloudtuya/package.json
```

**Comment by unparagoned** [comment]
Also if you still have an issue can you open an issue on https://github.com/unparagoned/njsTuya
