### ISSUE TITLE
TypeError: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by ameer1234567890** [unparagoned/cloudtuya#17]
I tried getting the state of a switch via `isOn()` function using `BaseDevice({ api, deviceId })` an I get the below error message:
```
(node:20682) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'state' of undefined
    at BaseDevice.isOn (/mnt/usb2/cloudtuya/devices/baseDevice.js:28:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20682) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20682) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by unparagoned** [comment]
Can you run with ```DEBUG=* node YOURSCRIPT.js```

**Comment by ameer1234567890** [comment]
```
  cloudtuya booting cloudtuya +0ms
  cloudtuya device data [{"data":{"online":true,"state":true},"name":"Tank","icon":"https://images.tuyaeu.com/smart/icon/1547005181rmegd2nader_0.png","id":"____________","dev_type":"switch","ha_type":"switch"},{"data":{},"name":"PIR Battery Low","id":"______________","dev_type":"scene","ha_type":"scene"}] +30ms
  cloudtuya {"access_token":"__________________","refresh_token":"_______________________","token_type":"bearer","expires_in":864000} +0ms
  cloudtuya { access_token: '_______________________',
  cloudtuya   refresh_token: '_______________________',
  cloudtuya   token_type: 'bearer',
  cloudtuya   expires_in: 864000 } +5ms
  cloudtuya Token {"access_token":"_______________________","refresh_token":"_______________________","token_type":"bearer","expires_in":864000} +2s
  cloudtuya { payload: { devices: [ [Object], [Object] ], scenes: [] },
  cloudtuya   header: { code: 'SUCCESS', payloadVersion: 1 } } +1s
  cloudtuya [ { data: { online: true, state: true },
  cloudtuya     name: 'Tank',
  cloudtuya     icon:
  cloudtuya      'https://images.tuyaeu.com/smart/icon/1547005181rmegd2nader_0.png',
  cloudtuya     id: '_______________________',
  cloudtuya     dev_type: 'switch',
  cloudtuya     ha_type: 'switch' },
  cloudtuya   { data: {},
  cloudtuya     name: 'PIR Battery Low',
  cloudtuya     id: '_______________________',
  cloudtuya     dev_type: 'scene',
  cloudtuya     ha_type: 'scene' } ] +8ms
  cloudtuya devices [{"data":{"online":true,"state":true},"name":"Tank","icon":"https://images.tuyaeu.com/smart/icon/1547005181rmegd2nader_0.png","id":"_______________________","dev_type":"switch","ha_type":"switch"},{"data":{},"name":"PIR Battery Low","id":"_______________________","dev_type":"scene","ha_type":"scene"}] +1s
  cloudtuya Data [{"data":{"online":true,"state":true},"name":"Tank","icon":"https://images.tuyaeu.com/smart/icon/1547005181rmegd2nader_0.png","id":"_______________________","dev_type":"switch","ha_type":"switch"},{"data":{},"name":"PIR Battery Low","id":"_______________________","dev_type":"scene","ha_type":"scene"}] +2ms
devices [{"data":{"online":true,"state":true},"name":"Tank","icon":"https://images.tuyaeu.com/smart/icon/1547005181rmegd2nader_0.png","id":"_______________________","dev_type":"switch","ha_type":"switch"},{"data":{},"name":"PIR Battery Low","id":"_______________________","dev_type":"scene","ha_type":"scene"}]
  cloudtuya The file ./devices.json was saved! +47ms
  cloudtuya { payload: {},
  cloudtuya   header:
  cloudtuya    { msg: 'you can discovery once in 600 seconds',
  cloudtuya      code: 'FrequentlyInvoke',
  cloudtuya      payloadVersion: 1 } } +2s
  cloudtuya undefined +3ms
(node:21487) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'state' of undefined
    at BaseDevice.isOn (/mnt/usb2/cloudtuya/devices/baseDevice.js:28:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21487) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21487) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ameer1234567890** [comment]
This is my code:
```
/**
* Example script using cloudtuya to connect, get states an change them
*/

const debug = require('debug')('cloudtuya');
const fs = require('fs');
const CloudTuya = require('./cloudtuya');
const BaseDevice = require('./devices/baseDevice');

const name = 'cloudtuya';

debug('booting %s', name);
// Load local files
let apiKeys = {};
let deviceData = {};
try {
  apiKeys = require('./keys.json');
} catch(err) {
  console.error('keys.json is missing.');
}
try {
  deviceData = require('./devices.json');
} catch(err) {
  console.warn('devices.json is missing. creating temporary');
  deviceData = [{ id: '10000000000', name: 'temp' }];
}
/**
* Save Data Such a Devices to file
* @param {Object} data to save
* @param {String} [file="./devices.json"] to save to
*/
function saveDataToFile(data, file = './devices.json') {
  debug(`Data ${JSON.stringify(data)}`);
  fs.writeFile(file, JSON.stringify(data), (err) => {
    if(err) {
      return debug(err);
    }
    debug(`The file ${file} was saved!`);
    return (file);
  });
}

// Load from keys.json
const api = new CloudTuya({
  userName: apiKeys.userName,
  password: apiKeys.password,
  bizType: apiKeys.bizType,
  countryCode: apiKeys.countryCode,
  region: apiKeys.region,
});



async function findDevices() {
  // Get all devices registered on the Tuya app
  let devices = await api.find();
  debug(`devices ${JSON.stringify(devices)}`);

  // Save device to device.json
  saveDataToFile(devices);
  console.log(`devices ${JSON.stringify(devices)}`);
  return devices;
}


async function getState(devId) {
  // Get state of a single device
  const deviceStates = await api.state({
    devId,
  });
  const state = deviceStates.devId;
  debug(`devices ${JSON.stringify(deviceStates)}`);
  console.log(state);
}

async function switchControl(deviceId) {
  // Example how to turn on a lamp and set brightness
  var mySwitch = new BaseDevice({ api, deviceId });

  // mySwitch.turnOn();
  // mySwitch.turnOff();

  var isOn = (JSON.stringify(await mySwitch.isOn()));

  console.log(`switch on: ${isOn}`);

}


async function main() {


  // Test device read from devices.json saved at the end.

  debug(`device data ${JSON.stringify(deviceData)}`);

  // Connect to cloud api and get access token.
  const tokens = await api.login();
  debug(`Token ${JSON.stringify(tokens)}`);


  /**
   * Initial find and save devices
   * */
  deviceData = await findDevices();

  /**
   * Get state
   * Before running comment out findDevices line above(tuya rate limit)
   */
  // await getState(deviceData[0].id);

  /**
   * For light control
   */
  await switchControl(deviceData[0].id);
}

main();
```

**Comment by unparagoned** [comment]
With the tuya rate-limiting, most of the code relating to toggling the state won't work. The isOn function tries to get the state again after the initial findDevices, which is causing your problem. 

Try and just turn devices on or off rather than checking their state beforehand. Or skip the findDevices() function, then you can get the state and then set it.

**Comment by ameer1234567890** [comment]
OK. So it is a rate-limiting issue. I got it working now. Thank you so much for the help.
