### ISSUE TITLE
Cannot read property map of undefined

### ISSUE THREAD

**Issue by pinpox** [unparagoned/cloudtuya#9]
Hello, 

I followed the example in the readme, but get an error:

```
(node:46601) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at CloudTuya.state (/home/binaryplease/homebridge-docker/cloudtuya/cloudtuya.js:154:37)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/home/binaryplease/homebridge-docker/cloudtuya/example.js:73:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:46601) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46601) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by unparagoned** [comment]
This is due to the fact tuya have a rate limit on the find function. The example script uses it to find the devices and then again to get the state, this errors out. 
Try the latest version and the error should be gone.
